# Generated by Django 5.0.14 on 2025-06-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofsale',
            name='warehouse',
        ),
    ]
